services:
  ynk-modelo:
    image: ynk-modelo:latest
    container_name: ynk-modelo
    environment:
      - ENVIRONMENT=prod
      - AUTO_REGENERATE=true
      - CHECK_INTERVAL=300
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    ports:
      - '${PORT:-8000}:8000'
